### ISSUE TITLE
event error.txt

### ISSUE THREAD

**Issue by rfikki** [Dsus4/truffle-init-angular#1]
Rocky@ASUS MINGW64 /c/projects/dapps
$ cd angular/truffle-angular

Rocky@ASUS MINGW64 /c/projects/dapps/angular/truffle-angular
$ ls
bs-config.aot.json  bs-config.json  contracts/  migrations/  package.json  README.md  src/  test/  truffle.js  tslint.json

Rocky@ASUS MINGW64 /c/projects/dapps/angular/truffle-angular
$ npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

> phantomjs-prebuilt@2.1.14 install C:\projects\dapps\angular\truffle-angular\node_modules\phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-windows.zip
Saving to C:\Users\Rocky\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip
Receiving...

Received 17767K total.
Extracting zip contents
Removing C:\projects\dapps\angular\truffle-angular\node_modules\phantomjs-prebuilt\lib\phantom
Copying extracted folder C:\Users\Rocky\AppData\Local\Temp\phantomjs\phantomjs-2.1.1-windows.zip-extract-1496939497813\phantomjs-2.1.1-windows -> C:\projects\dapps\angular\truffle-angular\node_modules\phantomjs-prebuilt\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\projects\dapps\angular\truffle-angular\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
truffle-init-angular@0.0.1 C:\projects\dapps\angular\truffle-angular
+-- @angular/animations@4.0.3
+-- @angular/common@4.0.3
+-- @angular/compiler@4.0.3
+-- @angular/compiler-cli@4.0.3
| +-- minimist@1.2.0
| `-- reflect-metadata@0.1.10
+-- @angular/core@4.0.3
+-- @angular/forms@4.0.3
+-- @angular/http@4.0.3
+-- @angular/platform-browser@4.0.3
+-- @angular/platform-browser-dynamic@4.0.3
+-- @angular/platform-server@4.0.3
| +-- parse5@3.0.2
| `-- xhr2@0.1.4
+-- @angular/router@4.0.3
+-- @angular/tsc-wrapped@4.0.3
| `-- tsickle@0.21.6
+-- @angular/upgrade@4.0.3
+-- @types/angular@1.6.18
| `-- @types/jquery@2.0.46
+-- @types/angular-animate@1.5.6
+-- @types/angular-cookies@1.4.3
+-- @types/angular-mocks@1.5.9
+-- @types/angular-resource@1.5.8
+-- @types/angular-route@1.3.3
+-- @types/angular-sanitize@1.3.4
+-- @types/jasmine@2.5.36
+-- @types/node@6.0.78
+-- angular-in-memory-web-api@0.3.2
+-- babel-cli@6.24.1
| +-- babel-core@6.24.1
| | +-- babel-code-frame@6.22.0
| | | +-- esutils@2.0.2
| | | `-- js-tokens@3.0.1
| | +-- babel-generator@6.24.1
| | | +-- detect-indent@4.0.0
| | | | `-- repeating@2.0.1
| | | |   `-- is-finite@1.0.2
| | | +-- jsesc@1.3.0
| | | `-- trim-right@1.0.1
| | +-- babel-helpers@6.24.1
| | +-- babel-messages@6.23.0
| | +-- babel-template@6.24.1
| | +-- babel-traverse@6.24.1
| | | +-- globals@9.18.0
| | | `-- invariant@2.2.2
| | |   `-- loose-envify@1.3.1
| | +-- babel-types@6.24.1
| | | `-- to-fast-properties@1.0.3
| | +-- babylon@6.17.2
| | +-- debug@2.6.8
| | | `-- ms@2.0.0
| | +-- json5@0.5.1
| | `-- private@0.1.7
| +-- babel-polyfill@6.23.0
| | `-- regenerator-runtime@0.10.5
| +-- babel-register@6.24.1
| | `-- home-or-tmp@2.0.0
| |   `-- os-homedir@1.0.2
| +-- babel-runtime@6.23.0
| +-- chokidar@1.7.0
| | +-- anymatch@1.3.0
| | | `-- arrify@1.0.1
| | +-- async-each@1.0.1
| | +-- glob-parent@2.0.0
| | +-- inherits@2.0.3
| | +-- is-binary-path@1.0.1
| | | `-- binary-extensions@1.8.0
| | +-- is-glob@2.0.1
| | | `-- is-extglob@1.0.0
| | `-- readdirp@2.1.0
| |   +-- readable-stream@2.2.11
| |   | +-- isarray@1.0.0
| |   | +-- process-nextick-args@1.0.7
| |   | `-- string_decoder@1.0.2
| |   `-- set-immediate-shim@1.0.1
| +-- commander@2.9.0
| | `-- graceful-readlink@1.0.1
| +-- convert-source-map@1.5.0
| +-- fs-readdir-recursive@1.0.0
| +-- glob@7.1.2
| | +-- fs.realpath@1.0.0
| | +-- inflight@1.0.6
| | | `-- wrappy@1.0.2
| | `-- once@1.4.0
| +-- output-file-sync@1.1.2
| | `-- object-assign@4.1.1
| +-- path-is-absolute@1.0.1
| +-- slash@1.0.0
| +-- source-map@0.5.6
| `-- v8flags@2.1.1
|   `-- user-home@1.1.1
+-- babel-preset-angular2@0.0.2
| +-- babel-plugin-angular2-annotations@5.1.0
| +-- babel-plugin-transform-class-properties@6.24.1
| | +-- babel-helper-function-name@6.24.1
| | `-- babel-plugin-syntax-class-properties@6.13.0
| +-- babel-plugin-transform-decorators-legacy@1.3.4
| | `-- babel-plugin-syntax-decorators@6.13.0
| `-- babel-plugin-transform-flow-strip-types@6.22.0
|   `-- babel-plugin-syntax-flow@6.18.0
+-- babel-preset-es2015@6.24.1
| +-- babel-plugin-check-es2015-constants@6.22.0
| +-- babel-plugin-transform-es2015-arrow-functions@6.22.0
| +-- babel-plugin-transform-es2015-block-scoped-functions@6.22.0
| +-- babel-plugin-transform-es2015-block-scoping@6.24.1
| +-- babel-plugin-transform-es2015-classes@6.24.1
| | +-- babel-helper-define-map@6.24.1
| | +-- babel-helper-optimise-call-expression@6.24.1
| | `-- babel-helper-replace-supers@6.24.1
| +-- babel-plugin-transform-es2015-computed-properties@6.24.1
| +-- babel-plugin-transform-es2015-destructuring@6.23.0
| +-- babel-plugin-transform-es2015-duplicate-keys@6.24.1
| +-- babel-plugin-transform-es2015-for-of@6.23.0
| +-- babel-plugin-transform-es2015-function-name@6.24.1
| +-- babel-plugin-transform-es2015-literals@6.22.0
| +-- babel-plugin-transform-es2015-modules-amd@6.24.1
| +-- babel-plugin-transform-es2015-modules-commonjs@6.24.1
| | `-- babel-plugin-transform-strict-mode@6.24.1
| +-- babel-plugin-transform-es2015-modules-systemjs@6.24.1
| | `-- babel-helper-hoist-variables@6.24.1
| +-- babel-plugin-transform-es2015-modules-umd@6.24.1
| +-- babel-plugin-transform-es2015-object-super@6.24.1
| +-- babel-plugin-transform-es2015-parameters@6.24.1
| | +-- babel-helper-call-delegate@6.24.1
| | `-- babel-helper-get-function-arity@6.24.1
| +-- babel-plugin-transform-es2015-shorthand-properties@6.24.1
| +-- babel-plugin-transform-es2015-spread@6.22.0
| +-- babel-plugin-transform-es2015-sticky-regex@6.24.1
| | `-- babel-helper-regex@6.24.1
| +-- babel-plugin-transform-es2015-template-literals@6.22.0
| +-- babel-plugin-transform-es2015-typeof-symbol@6.23.0
| +-- babel-plugin-transform-es2015-unicode-regex@6.24.1
| | `-- regexpu-core@2.0.0
| |   +-- regenerate@1.3.2
| |   +-- regjsgen@0.2.0
| |   `-- regjsparser@0.1.5
| |     `-- jsesc@0.5.0
| `-- babel-plugin-transform-regenerator@6.24.1
|   `-- regenerator-transform@0.9.11
+-- bootstrap@3.3.7
+-- bootstrap-material-design@0.5.10
+-- canonical-path@0.0.2
+-- concurrently@3.4.0
| +-- chalk@0.5.1
| | +-- ansi-styles@1.1.0
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@0.1.0
| | | `-- ansi-regex@0.2.1
| | +-- strip-ansi@0.3.0
| | `-- supports-color@0.2.0
| +-- commander@2.6.0
| +-- date-fns@1.28.5
| +-- rx@2.3.24
| +-- spawn-command@0.0.2-1
| +-- supports-color@3.2.3
| | `-- has-flag@1.0.0
| `-- tree-kill@1.1.0
+-- core-js@2.4.1
+-- http-server@0.9.0
| +-- colors@1.0.3
| +-- corser@2.0.1
| +-- ecstatic@1.4.1
| | +-- he@0.5.0
| | `-- url-join@1.1.0
| +-- http-proxy@1.16.2
| | +-- eventemitter3@1.2.0
| | `-- requires-port@1.0.0
| +-- opener@1.4.3
| +-- optimist@0.6.1
| | +-- minimist@0.0.10
| | `-- wordwrap@0.0.3
| +-- portfinder@0.4.0
| | `-- async@0.9.0
| `-- union@0.4.6
|   `-- qs@2.3.3
+-- jasmine@2.4.1
| +-- exit@0.1.2
| `-- glob@3.2.11
|   `-- minimatch@0.3.0
|     +-- lru-cache@2.7.3
|     `-- sigmund@1.0.1
+-- jasmine-core@2.4.1
+-- jquery@1.12.4
+-- karma@1.7.0
| +-- bluebird@3.5.0
| +-- body-parser@1.17.2
| | +-- bytes@2.4.0
| | +-- content-type@1.0.2
| | +-- debug@2.6.7
| | +-- depd@1.1.0
| | +-- http-errors@1.6.1
| | | +-- setprototypeof@1.0.3
| | | `-- statuses@1.3.1
| | +-- iconv-lite@0.4.15
| | +-- on-finished@2.3.0
| | | `-- ee-first@1.1.1
| | +-- qs@6.4.0
| | +-- raw-body@2.2.0
| | | `-- unpipe@1.0.0
| | `-- type-is@1.6.15
| |   `-- media-typer@0.3.0
| +-- colors@1.1.2
| +-- combine-lists@1.0.1
| +-- connect@3.6.2
| | +-- debug@2.6.7
| | +-- finalhandler@1.0.3
| | | +-- debug@2.6.7
| | | +-- encodeurl@1.0.1
| | | `-- escape-html@1.0.3
| | +-- parseurl@1.3.1
| | `-- utils-merge@1.0.0
| +-- di@0.0.1
| +-- dom-serialize@2.2.1
| | +-- custom-event@1.0.1
| | +-- ent@2.2.0
| | +-- extend@3.0.1
| | `-- void-elements@2.0.1
| +-- expand-braces@0.1.2
| | +-- array-slice@0.2.3
| | +-- array-unique@0.2.1
| | `-- braces@0.1.5
| |   `-- expand-range@0.1.1
| |     +-- is-number@0.1.1
| |     `-- repeat-string@0.2.2
| +-- graceful-fs@4.1.11
| +-- isbinaryfile@3.0.2
| +-- lodash@3.10.1
| +-- log4js@0.6.38
| | +-- readable-stream@1.0.34
| | | +-- core-util-is@1.0.2
| | | +-- isarray@0.0.1
| | | `-- string_decoder@0.10.31
| | `-- semver@4.3.6
| +-- mime@1.3.6
| +-- minimatch@3.0.4
| | `-- brace-expansion@1.1.7
| |   +-- balanced-match@0.4.2
| |   `-- concat-map@0.0.1
| +-- qjobs@1.1.5
| +-- range-parser@1.2.0
| +-- rimraf@2.6.1
| +-- safe-buffer@5.0.1
| +-- socket.io@1.7.3
| | +-- debug@2.3.3
| | | `-- ms@0.7.2
| | +-- engine.io@1.8.3
| | | +-- accepts@1.3.3
| | | | `-- negotiator@0.6.1
| | | +-- base64id@1.0.0
| | | +-- cookie@0.3.1
| | | +-- debug@2.3.3
| | | | `-- ms@0.7.2
| | | `-- engine.io-parser@1.3.2
| | |   +-- after@0.8.2
| | |   +-- arraybuffer.slice@0.0.6
| | |   +-- base64-arraybuffer@0.1.5
| | |   +-- blob@0.0.4
| | |   `-- wtf-8@1.0.0
| | +-- has-binary@0.1.7
| | | `-- isarray@0.0.1
| | +-- object-assign@4.1.0
| | +-- socket.io-adapter@0.5.0
| | | `-- debug@2.3.3
| | |   `-- ms@0.7.2
| | +-- socket.io-client@1.7.3
| | | +-- backo2@1.0.2
| | | +-- component-bind@1.0.0
| | | +-- component-emitter@1.2.1
| | | +-- debug@2.3.3
| | | | `-- ms@0.7.2
| | | +-- engine.io-client@1.8.3
| | | | +-- component-emitter@1.2.1
| | | | +-- component-inherit@0.0.3
| | | | +-- debug@2.3.3
| | | | | `-- ms@0.7.2
| | | | +-- has-cors@1.1.0
| | | | +-- parsejson@0.0.3
| | | | +-- parseqs@0.0.5
| | | | +-- xmlhttprequest-ssl@1.5.3
| | | | `-- yeast@0.1.2
| | | +-- indexof@0.0.1
| | | +-- object-component@0.0.3
| | | +-- parseuri@0.0.5
| | | | `-- better-assert@1.0.2
| | | |   `-- callsite@1.0.0
| | | `-- to-array@0.1.4
| | `-- socket.io-parser@2.3.1
| |   +-- component-emitter@1.1.2
| |   +-- debug@2.2.0
| |   | `-- ms@0.7.1
| |   +-- isarray@0.0.1
| |   `-- json3@3.3.2
| +-- tmp@0.0.31
| | `-- os-tmpdir@1.0.2
| `-- useragent@2.1.13
|   `-- lru-cache@2.2.4
+-- karma-chrome-launcher@2.1.1
| +-- fs-access@1.0.1
| | `-- null-check@1.0.0
| `-- which@1.2.14
|   `-- isexe@2.0.0
+-- karma-cli@1.0.1
| `-- resolve@1.3.3
|   `-- path-parse@1.0.5
+-- karma-jasmine@1.1.0
+-- karma-jasmine-html-reporter@0.2.2
+-- karma-phantomjs-launcher@1.0.4
+-- lite-server@2.3.0
| +-- browser-sync@2.18.12
| | +-- browser-sync-client@2.5.1
| | | +-- etag@1.8.0
| | | `-- fresh@0.3.0
| | +-- browser-sync-ui@0.6.3
| | | +-- async-each-series@0.1.1
| | | +-- stream-throttle@0.1.3
| | | | `-- limiter@1.1.0
| | | `-- weinre@2.0.0-pre-I0Z7U9OV
| | |   +-- express@2.5.11
| | |   | +-- connect@1.9.2
| | |   | | `-- formidable@1.0.17
| | |   | +-- mime@1.2.4
| | |   | +-- mkdirp@0.3.0
| | |   | `-- qs@0.4.2
| | |   +-- nopt@3.0.6
| | |   | `-- abbrev@1.1.0
| | |   `-- underscore@1.7.0
| | +-- bs-recipes@1.3.4
| | +-- connect@3.5.0
| | | +-- debug@2.2.0
| | | | `-- ms@0.7.1
| | | `-- finalhandler@0.5.0
| | +-- dev-ip@1.0.1
| | +-- easy-extender@2.3.2
| | | `-- lodash@3.10.1
| | +-- eazy-logger@3.0.2
| | | `-- tfunk@3.1.0
| | |   `-- object-path@0.9.2
| | +-- emitter-steward@1.0.0
| | +-- fs-extra@3.0.1
| | | +-- jsonfile@3.0.0
| | | `-- universalify@0.1.0
| | +-- http-proxy@1.15.2
| | +-- immutable@3.8.1
| | +-- localtunnel@1.8.2
| | | +-- debug@2.2.0
| | | | `-- ms@0.7.1
| | | +-- openurl@1.1.0
| | | +-- request@2.78.0
| | | | +-- node-uuid@1.4.8
| | | | `-- qs@6.3.2
| | | `-- yargs@3.29.0
| | |   `-- window-size@0.1.4
| | +-- micromatch@2.3.11
| | | +-- arr-diff@2.0.0
| | | | `-- arr-flatten@1.0.3
| | | +-- braces@1.8.5
| | | | +-- expand-range@1.8.2
| | | | | `-- fill-range@2.2.3
| | | | |   +-- is-number@2.1.0
| | | | |   +-- isobject@2.1.0
| | | | |   +-- randomatic@1.1.6
| | | | |   `-- repeat-string@1.6.1
| | | | +-- preserve@0.2.0
| | | | `-- repeat-element@1.1.2
| | | +-- expand-brackets@0.1.5
| | | | `-- is-posix-bracket@0.1.1
| | | +-- extglob@0.3.2
| | | +-- filename-regex@2.0.1
| | | +-- kind-of@3.2.2
| | | | `-- is-buffer@1.1.5
| | | +-- normalize-path@2.1.1
| | | | `-- remove-trailing-separator@1.0.2
| | | +-- object.omit@2.0.1
| | | | +-- for-own@0.1.5
| | | | | `-- for-in@1.0.2
| | | | `-- is-extendable@0.1.1
| | | +-- parse-glob@3.0.4
| | | | +-- glob-base@0.3.0
| | | | `-- is-dotfile@1.0.3
| | | `-- regex-cache@0.4.3
| | |   +-- is-equal-shallow@0.1.3
| | |   `-- is-primitive@2.0.0
| | +-- opn@4.0.2
| | +-- portscanner@2.1.1
| | | +-- async@1.5.2
| | | `-- is-number-like@1.0.7
| | |   +-- bubleify@0.5.1
| | |   | `-- buble@0.12.5
| | |   |   +-- acorn@3.3.0
| | |   |   +-- acorn-jsx@3.0.1
| | |   |   +-- acorn-object-spread@1.0.0
| | |   |   `-- magic-string@0.14.0
| | |   `-- lodash.isfinite@3.3.2
| | +-- qs@6.2.1
| | +-- resp-modifier@6.0.2
| | +-- rx@4.1.0
| | +-- serve-index@1.8.0
| | | +-- batch@0.5.3
| | | +-- debug@2.2.0
| | | | `-- ms@0.7.1
| | | `-- http-errors@1.5.1
| | |   `-- setprototypeof@1.0.2
| | +-- serve-static@1.12.2
| | | `-- send@0.15.2
| | |   +-- debug@2.6.4
| | |   | `-- ms@0.7.3
| | |   +-- destroy@1.0.4
| | |   +-- fresh@0.5.0
| | |   +-- mime@1.3.4
| | |   `-- ms@1.0.0
| | +-- server-destroy@1.0.1
| | +-- socket.io@1.6.0
| | | +-- debug@2.3.3
| | | | `-- ms@0.7.2
| | | +-- engine.io@1.8.0
| | | | +-- base64id@0.1.0
| | | | +-- debug@2.3.3
| | | | | `-- ms@0.7.2
| | | | +-- engine.io-parser@1.3.1
| | | | | +-- after@0.8.1
| | | | | `-- has-binary@0.1.6
| | | | |   `-- isarray@0.0.1
| | | | `-- ws@1.1.1
| | | `-- object-assign@4.1.0
| | +-- socket.io-client@1.6.0
| | | +-- component-emitter@1.2.1
| | | +-- debug@2.3.3
| | | | `-- ms@0.7.2
| | | `-- engine.io-client@1.8.0
| | |   `-- debug@2.3.3
| | |     `-- ms@0.7.2
| | +-- ua-parser-js@0.7.12
| | `-- yargs@6.4.0
| |   +-- camelcase@3.0.0
| |   +-- cliui@3.2.0
| |   | `-- wrap-ansi@2.1.0
| |   +-- decamelize@1.2.0
| |   +-- get-caller-file@1.0.2
| |   +-- os-locale@1.4.0
| |   | `-- lcid@1.0.0
| |   |   `-- invert-kv@1.0.0
| |   +-- read-pkg-up@1.0.1
| |   | +-- find-up@1.1.2
| |   | | `-- path-exists@2.1.0
| |   | `-- read-pkg@1.1.0
| |   |   +-- load-json-file@1.1.0
| |   |   | +-- parse-json@2.2.0
| |   |   | | `-- error-ex@1.3.1
| |   |   | |   `-- is-arrayish@0.2.1
| |   |   | `-- strip-bom@2.0.0
| |   |   |   `-- is-utf8@0.2.1
| |   |   `-- path-type@1.1.0
| |   +-- require-directory@2.1.1
| |   +-- require-main-filename@1.0.1
| |   +-- set-blocking@2.0.0
| |   +-- string-width@1.0.2
| |   | +-- code-point-at@1.1.0
| |   | `-- is-fullwidth-code-point@1.0.0
| |   |   `-- number-is-nan@1.0.1
| |   +-- which-module@1.0.0
| |   +-- window-size@0.2.0
| |   +-- y18n@3.2.1
| |   `-- yargs-parser@4.2.1
| |     `-- camelcase@3.0.0
| +-- connect-history-api-fallback@1.3.0
| `-- connect-logger@0.0.1
|   `-- moment@2.18.1
+-- lodash@4.17.4
+-- phantomjs-prebuilt@2.1.14
| +-- es6-promise@4.0.5
| +-- extract-zip@1.5.0
| | +-- concat-stream@1.5.0
| | | +-- readable-stream@2.0.6
| | | | `-- string_decoder@0.10.31
| | | `-- typedarray@0.0.6
| | +-- debug@0.7.4
| | +-- mkdirp@0.5.0
| | | `-- minimist@0.0.8
| | `-- yauzl@2.4.1
| |   `-- fd-slicer@1.0.1
| |     `-- pend@1.2.0
| +-- fs-extra@1.0.0
| | +-- jsonfile@2.4.0
| | `-- klaw@1.3.1
| +-- hasha@2.2.0
| | +-- is-stream@1.1.0
| | `-- pinkie-promise@2.0.1
| |   `-- pinkie@2.0.4
| +-- kew@0.7.0
| +-- progress@1.1.8
| +-- request@2.79.0
| | +-- aws-sign2@0.6.0
| | +-- aws4@1.6.0
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@2.1.4
| | | `-- asynckit@0.4.0
| | +-- har-validator@2.0.6
| | | `-- is-my-json-valid@2.16.0
| | |   +-- generate-function@2.0.0
| | |   +-- generate-object-property@1.2.0
| | |   | `-- is-property@1.0.2
| | |   +-- jsonpointer@4.0.1
| | |   `-- xtend@4.0.1
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.4.0
| | | | +-- assert-plus@1.0.0
| | | | +-- extsprintf@1.0.2
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.3.6
| | | `-- sshpk@1.13.1
| | |   +-- asn1@0.2.3
| | |   +-- assert-plus@1.0.0
| | |   +-- bcrypt-pbkdf@1.0.1
| | |   +-- dashdash@1.14.1
| | |   | `-- assert-plus@1.0.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- getpass@0.1.7
| | |   | `-- assert-plus@1.0.0
| | |   +-- jsbn@0.1.1
| | |   `-- tweetnacl@0.14.5
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.15
| | | `-- mime-db@1.27.0
| | +-- oauth-sign@0.8.2
| | +-- qs@6.3.2
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.3.2
| | | `-- punycode@1.4.1
| | +-- tunnel-agent@0.4.3
| | `-- uuid@3.0.1
| `-- request-progress@2.0.1
|   `-- throttleit@1.0.0
+-- protractor@4.0.14
| +-- @types/q@0.0.32
| +-- @types/selenium-webdriver@2.53.37
| +-- adm-zip@0.4.7
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- jasminewd2@0.0.10
| +-- q@1.4.1
| +-- saucelabs@1.3.0
| | `-- https-proxy-agent@1.0.0
| |   `-- agent-base@2.1.1
| |     `-- semver@5.0.3
| +-- selenium-webdriver@2.53.3
| | +-- adm-zip@0.4.4
| | +-- tmp@0.0.24
| | +-- ws@1.1.2
| | | +-- options@0.0.6
| | | `-- ultron@1.0.2
| | `-- xml2js@0.4.4
| |   +-- sax@0.6.1
| |   `-- xmlbuilder@9.0.0
| +-- source-map-support@0.4.15
| `-- webdriver-manager@10.3.0
|   +-- del@2.2.2
|   | +-- globby@5.0.0
|   | | `-- array-union@1.0.2
|   | |   `-- array-uniq@1.0.3
|   | +-- is-path-cwd@1.0.0
|   | +-- is-path-in-cwd@1.0.0
|   | | `-- is-path-inside@1.0.0
|   | |   `-- path-is-inside@1.0.2
|   | `-- pify@2.3.0
|   +-- ini@1.3.4
|   `-- semver@5.3.0
+-- rollup@0.41.6
+-- rollup-plugin-commonjs@8.0.2
| +-- acorn@4.0.13
| +-- estree-walker@0.3.1
| +-- magic-string@0.19.1
| | `-- vlq@0.2.2
| `-- rollup-pluginutils@2.0.1
+-- rollup-plugin-node-resolve@2.0.0
| +-- browser-resolve@1.11.2
| | `-- resolve@1.1.7
| `-- builtin-modules@1.1.1
+-- rollup-plugin-uglify@1.0.2
| `-- uglify-js@2.8.28
|   +-- uglify-to-browserify@1.0.2
|   `-- yargs@3.10.0
|     +-- camelcase@1.2.1
|     +-- cliui@2.1.0
|     | +-- center-align@0.1.3
|     | | +-- align-text@0.1.4
|     | | | `-- longest@1.0.1
|     | | `-- lazy-cache@1.0.4
|     | +-- right-align@0.1.3
|     | `-- wordwrap@0.0.2
|     `-- window-size@0.1.0
+-- rxjs@5.0.1
| `-- symbol-observable@1.0.4
+-- source-map-explorer@1.3.3
| +-- btoa@1.1.2
| +-- docopt@0.6.2
| +-- file-url@1.1.0
| | `-- meow@3.7.0
| |   +-- camelcase-keys@2.1.0
| |   | `-- camelcase@2.1.1
| |   +-- loud-rejection@1.6.0
| |   | +-- currently-unhandled@0.4.1
| |   | | `-- array-find-index@1.0.2
| |   | `-- signal-exit@3.0.2
| |   +-- map-obj@1.0.1
| |   +-- normalize-package-data@2.3.8
| |   | +-- hosted-git-info@2.4.2
| |   | +-- is-builtin-module@1.0.0
| |   | `-- validate-npm-package-license@3.0.1
| |   |   +-- spdx-correct@1.0.2
| |   |   | `-- spdx-license-ids@1.2.2
| |   |   `-- spdx-expression-parse@1.0.4
| |   +-- redent@1.0.0
| |   | +-- indent-string@2.1.0
| |   | `-- strip-indent@1.0.1
| |   |   `-- get-stdin@4.0.1
| |   `-- trim-newlines@1.0.0
| +-- open@0.0.5
| +-- temp@0.8.3
| | `-- rimraf@2.2.8
| `-- underscore@1.8.3
+-- systemjs@0.19.39
| `-- when@3.7.8
+-- truffle-contract@1.1.11
| +-- ethjs-abi@0.1.8
| | +-- bn.js@4.11.6
| | +-- js-sha3@0.5.5
| | `-- number-to-bn@1.7.0
| |   `-- strip-hex-prefix@1.0.0
| |     `-- is-hex-prefixed@1.0.0
| +-- truffle-blockchain-utils@0.0.1
| +-- truffle-contract-schema@0.0.5
| | `-- crypto-js@3.1.9-1
| `-- web3@0.16.0
|   `-- bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
+-- tslint@3.15.1
| +-- colors@1.1.2
| +-- diff@2.2.3
| +-- findup-sync@0.3.0
| | `-- glob@5.0.15
| `-- underscore.string@3.3.4
|   +-- sprintf-js@1.1.1
|   `-- util-deprecate@1.0.2
+-- typescript@2.2.2
+-- web3@0.18.4
| +-- bignumber.js@2.0.7  (git+https://github.com/debris/bignumber.js.git#94d7146671b9719e00a09c29b01a691bc85048c2)
| +-- crypto-js@3.1.8
| +-- utf8@2.1.2
| `-- xmlhttprequest@1.8.0
+-- write@0.3.3
| +-- fs-exists-sync@0.1.0
| `-- mkdirp@0.5.1
|   `-- minimist@0.0.8
`-- zone.js@0.8.12

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

Rocky@ASUS MINGW64 /c/projects/dapps/angular/truffle-angular
$ truffle compile
Compiling .\contracts\ConvertLib.sol...
Compiling .\contracts\MetaCoin.sol...
Compiling .\contracts\Migrations.sol...
Writing artifacts to .\build\contracts

Rocky@ASUS MINGW64 /c/projects/dapps/angular/truffle-angular
$ truffle migrate
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  Migrations: 0x5e194b5ee93b932ea2cf8d9b69a240a26cbf05ff
Saving successful migration to network...
Saving artifacts...
Running migration: 2_deploy_contracts.js
  Deploying ConvertLib...
  ConvertLib: 0xe4e7a4be4b0ccc28c2c1d4b937c5c4091f05f692
  Linking ConvertLib to MetaCoin
  Deploying MetaCoin...
  MetaCoin: 0x74b4484643cee271ca0f3bd524aeaf1c7169b6e5
Saving successful migration to network...
Saving artifacts...

Rocky@ASUS MINGW64 /c/projects/dapps/angular/truffle-angular
$ truffle build
Running `npm start`...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Rocky@ASUS MINGW64 /c/projects/dapps/angular/truffle-angular
$ truffle serve
Serving static assets in .\build on port 8080...
Rebuilding...
C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:121784
  return (new fsevents(path)).on('fsevent', callback).start();
          ^

TypeError: fsevents is not a constructor
    at createFSEventsInstance (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:121784:11)
    at setFSEventsListener (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:121838:16)
    at FSWatcher.FsEventsHandler._watchWithFsEvents (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:122002:16)
    at FSWatcher.<anonymous> (C:\Users\Rocky\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:122136:25)
    at gotStat (fs.js:1637:21)
    at FSReqWrap.oncomplete (fs.js:112:15)

Rocky@ASUS MINGW64 /c/projects/dapps/angular/truffle-angular

**Comment by rfikki** [comment]
So, after some research found out that this is caused when using bash for windows. When using windows run the final npm start command from the terminal and it miraculously works.

**Comment by Dsus4** [comment]
Closed as it is a known issue with npm run scripts on windows:
https://github.com/nodejs/node/issues/3675
